apiVersion: v1
kind: Service
metadata:
  name: salonmanager-appointments-svc
  namespace: salonmanager-hom-ns
spec:
  type: ClusterIP
  selector:
    app: salonmanager-appointments
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
