apiVersion: v1
kind: Service
metadata:
  name: salonmanager-customers-db-svc
  namespace: salonmanager-hom-ns
spec:
  type: ClusterIP
  selector:
    app: salonmanager-customers-db
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
