apiVersion: v1
kind: Service
metadata:
  name: salonmanager-customers-svc
  namespace: salonmanager-hom-ns
spec:
  type: ClusterIP
  selector:
    app: salonmanager-customers
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
