apiVersion: v1
kind: Service
metadata:
  name: salonmanager-gateway-svc
  namespace: salonmanager-hom-ns
spec:
  type: NodePort
  selector:
    app: salonmanager-gateway
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31001
    
